{
  "button": [
  {    
    "name":"展会信息",
    "sub_button": [
      {
        "type":"view",
        "name":"展会概况",
        "url":"https://www.x-pingic.com/page/zhgk/index.html"
      },
      {
        "type":"view",
        "name":"展会架构",
        "url":"https://www.x-pingic.com/page/structure/index.html"
      },
      {
        "type":"view",
        "name":"新闻资讯",
        "url":"https://www.x-pingic.com/post/index/"
      },
      {
        "type":"view",
        "name":"联系我们",
        "url":"https://www.x-pingic.com/page/lxwm/"
      }
    ]    
  },
  {
    "type":"view",
     "name":"2018矿业展",
     "url":"https://www.x-pingic.com/countdownone.html"    
  },
  {
    "type":"view",
     "name":"地球脉动",
     "url":"https://www.bagevent.com/event/2014459"    
  }
  ]
}