{
  "button": [
  {    
    "name":"展会信息",
    "sub_button": [
      {
        "type":"view",
        "name":"展会概况",
        "url":"http://www.pingic.tech:8083/page/zhgk/index.html"
      },
      {
        "type":"view",
        "name":"展会架构",
        "url":"http://www.pingic.tech:8083"
      },
      {
        "type":"view",
        "name":"新闻资讯",
        "url":"http://www.pingic.tech:8083"
      },
      {
        "type":"view",
        "name":"联系我们",
        "url":"http://www.pingic.tech:8083"
      }
    ]    
  },
  {
    "type":"view",
     "name":"2018矿业展",
     "url":"http://www.pingic.tech:8083/countdownone.html"    
  },
  {    
    "name":"参展动态",
    "sub_button": [
      {
        "type":"view",
        "name":"参展企业",
        "url":"http://www.pingic.tech:8083"
      },
      {
        "type":"view",
        "name":"发现宝物",
        "url":"http://www.pingic.tech:8083"
      }
    ]    
  }
  ]
}